# Generated by Django 4.1.4 on 2023-01-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_ordermodel_created_date_alter_ordermodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='created_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
