# Generated by Django 3.1.7 on 2021-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='totalAmount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
