# Generated by Django 3.1.7 on 2021-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_auto_20210428_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='totalAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
